import fs from 'node:fs';
import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('../public/index.html',import.meta.url),'utf8');
const worker=fs.readFileSync(new URL('../public/_worker.js',import.meta.url),'utf8');
assert.match(html,/Historique de mes demandes/);
assert.match(html,/\+ Nouvelle demande/);
assert.match(html,/Nouvelle demande de correction/);
assert.match(html,/openCorrectionRequestModal/);
assert.match(html,/hiddenAdminButtons=new Set\(\['utilisateurs','mailbox','notifications'\]\)/);
assert.match(html,/Liste des crédits/);
assert.match(html,/Nouveau compte crédit/);
assert.match(html,/Paiement crédit/);
assert.match(html,/visibleReportSections=\['revenus','obligations','point_types'\]/);
assert.doesNotMatch(html,/reportButtons[^`]*Point détaillé des crédits[^`]*Comptes bancaires[^`]*Historique détaillé des opérations/);
assert.match(html,/PERMISSION_LABELS/);
assert.match(html,/Autorisations supplémentaires/);
assert.match(html,/Restrictions individuelles/);
assert.match(html,/userCompactTable/);
assert.match(html,/role-admin_bank \.topbar\{display:flex!important;flex-wrap:nowrap!important/);
assert.match(worker,/auditeur:\['clients\.read','accounts\.read','moves\.read','credits\.read','reports\.read\.limited','documents\.print','correction\.request','profile\.read\.own'\]/);
assert.match(worker,/operation_requests:\(requestQ\.results\|\|\[\]\)\.filter\(r=>String\(r\.requested_by\)===uidValue\)/);
console.log('ALL UI ADMIN WORKFLOWS V12 TESTS PASSED');
