import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const html=await readFile(new URL('../public/index.html',import.meta.url),'utf8');
assert.match(html,/GLOBAL BANK V11 — INTERFACES PROFESSIONNELLES DES AGENTS/);
assert.match(html,/role-agent_credit/);
assert.match(html,/role-auditeur/);
assert.match(html,/const AGENT_NAV_META=/);
assert.match(html,/Tableau de bord Agent crédit/);
assert.match(html,/Dernières opérations crédit/);
assert.match(html,/Tableau de bord Auditeur/);
assert.match(html,/Dernières opérations consultables/);
assert.match(html,/Espace Auditeur activé — consultation et impression uniquement/);
assert.match(html,/\['agent_caisse','agent_credit','auditeur'\]\.includes\(key\)/);
const menuBlock=html.match(/const ROLE_MENUS=\{[\s\S]*?\n\};/);
assert.ok(menuBlock,'ROLE_MENUS introuvable');
assert.doesNotMatch(menuBlock[0],/'logout'/);
assert.equal((html.match(/class="logoutProfile"/g)||[]).length,1);
assert.doesNotMatch(menuBlock[0],/agent_credit:\s*\[[^\]]*parametres/s);
assert.doesNotMatch(menuBlock[0],/auditeur:\s*\[[^\]]*(?:credit|caisse|parametres)/s);
assert.match(menuBlock[0],/auditeur:\s*\[[^\]]*corrections/s);
console.log('ALL AGENT DASHBOARDS V11 UI TESTS PASSED');
